%% Emmanuel Taylor, Chris Glenn, Erin Tumney
%  MATH461 - Linear Algebra for Scientists and Engineers
%  Sections: 0111, 0112, 0114
%  May 9, 2014
%  Matlab Assignment 4

%% Problem 1
%  For the following matrix, complete the following tasks.
A = [1.52 -0.7;0.56 0.4]

%%
% *PROBLEM 1 PART A:*
%
%  For the above matrix, use an appropriate MATLAB function, find
%  the eigenvalues of A. Find the largest absolute value for the eigenvalues
%  of A (that is, compute the absolute value for real eigenvalue or the
%  modulus for complex eigenvalues, and report back the largest computed
%  value).
lambdaA = eig(A)
absValueA = abs(lambdaA)

%%
%  As you can see, the eigenvalues for the matrix A are the complex
%  conjugates of one another, therefore, they have the same absolute value.
%  The modulus for the complex eigenvalues is 1, which is the largest
%  computed value.

%%
% *PROBLEM 1 PART B:*
%
%  Compute the first 50 terms of the sequence {xk} defined by the
%  recursive relation x0 = [1 0]'; xk+1 = Axk. Display the terms x10, 
%  x_20, x30, x40, x50.
x = [1;0];
xk = [x];
for i = 1:49
    x = A*x;
    xk = [xk x];
end

x10 = [xk(1, 10);xk(2, 10)]
x20 = [xk(1, 20);xk(2, 20)]
x30 = [xk(1, 30);xk(2, 30)]
x40 = [xk(1, 40);xk(2, 40)]
x50 = [xk(1, 50);xk(2, 50)]

%%
% *PROBLEM 1 PART C:* 
%
%  Plot the points in the plane corresponding to the vectors xk,
%  generated in PART B using a point marker. Label your axis and title your
%  graph using MATLAB commands.
figure; hold on
for j = 1:49
    plot(xk(1, j), xk(2, j), 'Marker', '.')
end
hold off
title 'MATLAB Project 4 Problem 1 Part C'
xlabel 'X Coordinate of Vector x_k'
ylabel 'Y Coordinate of Vector x_k'

%%
% *PROBLEM 1 PART D:* 
%
%  Over the plot obtained in PART C, overlap the points
%  corresponding to xk for k = 0:4 marked with a circle, x-mark, plus, star,
%  and square markers, respectively. Add a legend to clarify which point is
%  which.
figure; hold on
for j = 1:49
    plot(xk(1, j), xk(2, j), 'Marker', '.')
end
x0 = plot(x(1, 1), x(2, 1), 'Marker', 'o', 'color', 'r');
x1 = plot(xk(1, 1), xk(2, 1), 'Marker', 'x', 'color', 'r');
x2 = plot(xk(1, 2), xk(2, 2), 'Marker', '+', 'color', 'r');
x3 = plot(xk(1, 3), xk(2, 3), 'Marker', '*', 'color', 'r');
x4 = plot(xk(1, 4), xk(2, 4), 'Marker', 's', 'color', 'r');
h = [x0 x1 x2 x3 x4];
plegend = legend(h, 'x_0', 'x_1', 'x_2', 'x_3', 'x_4');
set(plegend, 'Location', 'NorthWest')
hold off
title 'MATLAB Project 4 Problem 1 Part D'
xlabel 'X Coordinate of Vector x_k'
ylabel 'Y Coordinate of Vector x_k'

%% Problem 2
%  Repeat Problem 1 for the matrices B = [1 -2;1 3] and C = [.3 -.3;.1 -.1].
A = [1.52 -0.7;0.56 0.4]
B = [1 -2;1 3]
C = [.3 -.3;.1 -.1]

%%
% *PROBLEM 2 PART A:*
%
%  How do the graphs for the sequences generated by A, B, and C
%  differ from each other?
x = [1;0];
xk = [x];
for i = 1:49
    x = A*x;
    xk = [xk x];
end

figure; hold on
for j = 1:49
    plot(xk(1, j), xk(2, j), 'Marker', '.')
end
hold off
title 'MATLAB Project 4 Problem 2 Part A Graph A'
xlabel 'X Coordinate of Vector Xk'
ylabel 'Y Coordinate of Vector Xk'

x = [1;0];
xb = [x];
for i = 1:49
    x = B*x;
    xb = [xb x];
end

figure; hold on
for j = 1:49
    plot(xb(1, j), xb(2, j), 'Marker', '.')
end
hold off
title 'MATLAB Project 4 Problem 2 Part A Graph B'
xlabel 'X Coordinate of Vector Xb'
ylabel 'Y Coordinate of Vector Xb'

x = [1;0];
xc = [x];
for i = 1:49
    x = C*x;
    xc = [xc x];
end

figure; hold on
for j = 1:49
    plot(xc(1, j), xc(2, j), 'Marker', '.')
end
hold off
title 'MATLAB Project 4 Problem 2 Part A Graph C'
xlabel 'X Coordinate of Vector Xc'
ylabel 'Y Coordinate of Vector Xc'

xb10 = [xb(1, 10);xb(2, 10)]
xb20 = [xb(1, 20);xb(2, 20)]
xb30 = [xb(1, 30);xb(2, 30)]
xb40 = [xb(1, 40);xb(2, 40)]
xb50 = [xb(1, 50);xb(2, 50)]

xc10 = [xc(1, 10);xc(2, 10)]
xc20 = [xc(1, 20);xc(2, 20)]
xc30 = [xc(1, 30);xc(2, 30)]
xc40 = [xc(1, 40);xc(2, 40)]
xc50 = [xc(1, 50);xc(2, 50)]

figure; hold on
for j = 1:49
    plot(xb(1, j), xb(2, j), 'Marker', '.')
end
xb0 = plot(x(1, 1), x(2, 1), 'Marker', 'o', 'color', 'r');
xb1 = plot(xb(1, 1), xb(2, 1), 'Marker', 'x', 'color', 'r');
xb2 = plot(xb(1, 2), xb(2, 2), 'Marker', '+', 'color', 'r');
xb3 = plot(xb(1, 3), xb(2, 3), 'Marker', '*', 'color', 'r');
xb4 = plot(xb(1, 4), xb(2, 4), 'Marker', 's', 'color', 'r');
h = [xb0 xb1 xb2 xb3 xb4];
plegend = legend(h, 'x_b0', 'x_b1', 'x_b2', 'x_b3', 'x_b4');
set(plegend, 'Location', 'NorthWest')
hold off
title 'MATLAB Project 4 Problem 2 Part A Graph B'
xlabel 'X Coordinate of Vector x_b'
ylabel 'Y Coordinate of Vector x_b'

figure; hold on
for j = 1:49
    plot(xc(1, j), xc(2, j), 'Marker', '.')
end
xc0 = plot(x(1, 1), x(2, 1), 'Marker', 'o', 'color', 'r');
xc1 = plot(xc(1, 1), xc(2, 1), 'Marker', 'x', 'color', 'r');
xc2 = plot(xc(1, 2), xc(2, 2), 'Marker', '+', 'color', 'r');
xc3 = plot(xc(1, 3), xc(2, 3), 'Marker', '*', 'color', 'r');
xc4 = plot(xc(1, 4), xc(2, 4), 'Marker', 's', 'color', 'r');
h = [xc0 xc1 xc2 xc3 xc4];
plegend = legend(h, 'x_c0', 'x_c1', 'x_c2', 'x_c3', 'x_c4');
set(plegend, 'Location', 'NorthWest')
hold off
title 'MATLAB Project 4 Problem 2 Part A Graph C'
xlabel 'X Coordinate of Vector x_c'
ylabel 'Y Coordinate of Vector x_c'

%%
%  As you can see by the above plots, the graphs of the sequences for A, B,
%  and C differ greatly. Graph A seems to form an elliptical shape, Graph B
%  seems to form a curve, and Graph C seems to form a line.

%% 
% *PROBLEM 2 PART B:*
%
%  How do the largest absolute value for the eigenvalues of A, B,
%  and C differ?
lambdaA = eig(A)
absValueA = abs(lambdaA)

lambdaB = eig(B)
absValueB = abs(lambdaB)

lambdaC = eig(C)
absValueC = abs(lambdaC)

%% 
%  By looking at the computed values, the eigenvalues for A and B are the
%  complex conjugates of one another so each eigenvalue has the same
%  absolute value. B has a larger absolute value than A. The largest value
%  for the eigenvalue of C is 0.2 because the eigenvalues are real and have
%  different absolute values. 

%%
% *PROBLEM 2 PART C:*
%
%  Explain why you think that the graph for A looks different.

%  I think that the graph for A looks different because the eigenvalues are
%  complex conjugates of one another which causes the graph to be in the
%  shape of an oval.

%% Problem 3
%  In Detroit, Hertz Rent-A-Car has fleet of about 2000 cars. The pattern of
%  rental and return locations is given by the fractions in the matrix P.
P = [.9 .01 .09; .01 .90 .01; .09 .09 .9]

%%
% *PROBLEM 3 PART A:*
% 
%  A numerical vector with non-negative entries that add up to 1 is
%  called a probability vector. A stochastic matrix is a square matrix whose
%  columns are probability vectors. Using MATLAB, verify that P is a
%  stochastic matrix.
col1 = P(1, 1) + P(2, 1) + P(3, 1)
col2 = P(1, 2) + P(2, 2) + P(3, 2)
col3 = P(1, 3) + P(2, 3) + P(3, 3)

%%
%  As you can see, each column of the matrix P is a probability vector.
%  Therefore, P is a stochastic matrix.

%%
% *PROBLEM 3 PART B:*
% 
%  If P is a stochastic matrix, then a steady-state vector (or
%  equilibrium vector) for P is a probability vector q such that Pq = q.
%  What dose the equation Pq = q tell you about one of the eigenvalues of P
%  and its associated eigenvector?

%  The equation Pq = q matches the equation Av = lambda*v. This equation
%  tells us that 1 is an eigenvalue of P and it's corresponding eigenvector
%  is q.

%%
% *PROBLEM 3 PART C:*
%
%  Using MATLAB, find the eigenvalues and eigenvectors of P.
[V D] = eig(P)

%%
%  V is a matrix containing the eigenvectors of P while D is a diagonal
%  matrix containing the eigenvalues.

%%
% *PROBLEM 3 PART D:*
% 
%  Using PART C above, find v, an eigenvector of P corresponding to
%  Pq = q. If v is a probability vector, then v is a steady-state vector for
%  P; if not, scale v by the sum of its entries to obtain the steady-state
%  vector q. 
v = [abs(V(1, 1)); abs(V(2, 1)); abs(V(3, 1))]
scalingFactor = abs(V(1, 1) + V(2, 1) + V(3, 1))
q = (1 / scalingFactor) * v

%%
% *PROBLEM 3 PART E:*
% 
%  In our problem, the entries in the steady state vector q show
%  that the fractions of the cars rented or ready to rend on a typical day
%  from each of the locations (City Airport, Downtown, Metro Airport). On a
%  typical day, about how many cars will be rented of ready to rend from the
%  Downtown locations? Explain any approximation you make.
Total = 2000
Downtown = q(2, 1)
Rented = Total * Downtown

%%
%  About 182 cars will be ready to rent from the Downtown location. The
%  original number was 181.8182 but I rounded to 182.

%% Problem 4
%  When the right side of an equation Ax = b is changed slightly, say to Ax
%  = b + delta_b for some vector delta_b, the solution changes from x to x +
%  delta_x, where delta_x satisfies A*delta_x = delta_b. The quotient of
%  norms norm(delta_b)/norm(b) is called the relative change in b (or the
%  relative error in b where delta_b represents possible errors in the
%  entries of b). The relative change in the solution is
%  norm(delta_x)/norm(x). When A is invertible, the condition number of A,
%  written as cond(A), produce a bound on how large the relative change in x
%  can be: (norm(delta_x)/norm(x)) <= cond(A)*(norm(delta_b)/norm(b)).
A = [7 -6 -4 1;-5 1 0 -2;10 11 7 -3;19 9 7 1]
b1 = [4.230; -11.043; 49.991; 69.536]
delta_b1 = [.27; 7.76; -3.77; 3.93]*10^(-4)
b2 = [.100; 2.88; -1.404; 1.462]
delta_b2 = [.49; -1.28; 5.78; 8.04]*10^(-4)

%%
% *PROBLEM 4 PART A:*
%
%  Solve the equation Ax = b for both b1 and b2.
x1 = A\b1
x2 = A\b2

%%
% *PROBLEM 4 PART B:*
% 
%  Solve the equation A*delta_x = delta_b for both delta_b1 and
%  delta_b2.
delta_x1 = A\delta_b1
delta_x2 = A\delta_b2

%%
% *PROBLEM 4 PART C:*
%
%  Display x and delta_x
x = [x1 x2]
delta_x = [delta_x1 delta_x2]

%%
% *PROBLEM 4 PART D:*
% 
%  Compute and display the relative errors in b and in the solution.
b1Error = norm(delta_b1)/norm(b1)
b2Error = norm(delta_b2)/norm(b2)

x1Error = norm(delta_x1)/norm(x1)
x2Error = norm(delta_x2)/norm(x2)

%% 
% *PROBLEM 4 PART E:*
%
%  Show that the inequality holds in both cases.
leftSide1 = cond(A)*b1Error
x1Error = norm(delta_x1)/norm(x1)

leftSide2 = cond(A)*b2Error
x2Error = norm(delta_x2)/norm(x2)

%% 
%  Looking at the above calculations, it is easy to see that the inequality
%  holds for both cases.

%% Problem 5
%  A healthy child's systolic blood pressure p (in millimeters of mercury)
%  and weight w (in pounds) are approximately related by the equation Beta0
%  + Beta1*ln(w) = p.

%%
% *PROBLEM 5 PART A:*
%
%  Using the data from the table, generate a design matrix
%  corresponding to this model.
X = [1 3.78; 1 4.11; 1 4.39; 1 4.73; 1 4.78]

%%
% *PROBLEM 5 PART B:*
%
%  Generate the observation vector for this model.
y = [91; 98; 103; 110; 110]

%%
% *PROBLEM 5 PART C:*
%
%  Compute the parameter vector for the model and display it.
XX = X'*X
XY = X'*y
Beta = XX\XY

%%
% *PROBLEM 5 PART D:*
% 
%  Using the parameters in PART C, estimate and display the systolic
%  blood pressure of a healthy child weighing 100 pounds.
W = 100
w = log(W)
est_p = Beta(1, 1) + Beta(2, 1)*w

%%
% *PROBLEM 5 PART E:*
% 
%  On the same graph, plot the experimental data and the point
%  computed at PART D. Use different line styles or marker to distinguish
%  between the different data and a legend to identify which point is which.
X = [3.78 4.11 4.39 4.73 4.88];
Y = [91 98 103 110 110];
figure; hold on
plot(X, Y, 'Marker', 'o');
p = plot(w, est_p, 'Marker', 'x', 'color', 'r');
plegend = legend(p, 'Estimation');
set(plegend, 'Location', 'NorthWest')
axis([3.7 5 91 112])
xlabel 'Values for ln(w)'
ylabel 'Values for Observation Vector (p)'
title 'Estimated Point vs. Experimental Data'
grid
hold off