#!/usr/bin/env bash

# Script to run this test
# Usage: runme [no arguments]

# [FIXME: complete this script, this is just a template]

UXLIB=../../bin/behavioral

if [ -f out.txt ]; then
	rm -r out.txt
fi

vsim -c -L "$UXLIB" -lic_plus -quiet -novopt -do simulate-do testbench > transcript
diff out.txt correct-out1.txt

