###############################################################
# docker-compose.yml
#
# @author Emmanuel Taylor
# @author Ryan Tiffany
# @author Vincent Gruse
#
# @description
#   Creates the Docker network for the Party en mi Casa
#   application. Manages Docker storage volumes and services.
###############################################################

services:

  # Builds the image from the front end's Dockerfile and maps 
  # port 3000 to 80 in the container.
  frontend:
    build: ./frontend
    ports:
      - 3000:80

  # Builds the image for MongoDB using the official MongoDB image
  # from Docker Hub and attaches a named volume to persist data
  # from the database.
  mongo:
    image: docker.io/mongo
    volumes:
      - mongoDB:/data/db

  # Builds the image for Mongo-Express using the official Mongo-Express
  # image from Docker Hub, maps port 8081 to 8081 in the container, and
  # ensures Mongo-Express starts after the MongoDB service.
  mongo-express:
    image: docker.io/mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo

  # Builds the image from the back end's Dockerfile, maps ports 3002 and 3001
  # to ports 3002 and 3001 in the container, ensures the back end starts after
  # the MongoDB and Redis services, and loads environment variables from .env.
  backend:
    build: ./backend
    ports:
      - 3002:3002 # REST API
      - 3001:3001 # Websocket
    depends_on:
      - mongo
      - redis
    env_file:
      - .env

  # Builds the image for Redis using the official Redis image from Docker Hub.
  redis:
    image: docker.io/redis

# Define the named volumes for persistent storage.
volumes:
  mongoDB:
    external: true