
// Generated by Cadence Encounter(R) RTL Compiler v11.20-s017_1

// Verification Directory fv/ccu 

module adder(A, B, Sum, Cout);
  input [1:0] A, B;
  output [1:0] Sum;
  output Cout;
  wire [1:0] A, B;
  wire [1:0] Sum;
  wire Cout;
  wire n_0;
  FADDX1 g84(.A (B[1]), .B (A[1]), .CI (n_0), .S (Sum[1]), .CO (Cout));
  HADDX1 g85(.A0 (B[0]), .B0 (A[0]), .SO (Sum[0]), .C1 (n_0));
endmodule

module counter(clk, reset, out);
  input clk, reset;
  output [1:0] out;
  wire clk, reset;
  wire [1:0] out;
  wire UNCONNECTED, UNCONNECTED0, n_0, n_1, n_2, n_3;
  DFFX1 \out_reg[1] (.CLK (clk), .D (n_2), .Q (out[1]), .QN
       (UNCONNECTED));
  DFFX1 \out_reg[0] (.CLK (clk), .D (n_3), .Q (out[0]), .QN
       (UNCONNECTED0));
  NOR2X0 g81(.IN1 (n_1), .IN2 (out[0]), .QN (n_3));
  AND2X1 g82(.IN1 (n_0), .IN2 (out[0]), .Q (n_2));
  INVX0 g83(.INP (n_0), .ZN (n_1));
  NOR2X0 g84(.IN1 (out[1]), .IN2 (reset), .QN (n_0));
endmodule

module mux(Select, X, Y, Out);
  input Select;
  input [1:0] X, Y;
  output [1:0] Out;
  wire Select;
  wire [1:0] X, Y;
  wire [1:0] Out;
  MUX21X1 g33(.IN1 (X[1]), .IN2 (Y[1]), .S (Select), .Q (Out[1]));
  MUX21X1 g34(.IN1 (X[0]), .IN2 (Y[0]), .S (Select), .Q (Out[0]));
endmodule

module mux_1(Select, X, Y, Out);
  input Select;
  input [1:0] X, Y;
  output [1:0] Out;
  wire Select;
  wire [1:0] X, Y;
  wire [1:0] Out;
  MUX21X1 g33(.IN1 (X[1]), .IN2 (Y[1]), .S (Select), .Q (Out[1]));
  MUX21X1 g34(.IN1 (X[0]), .IN2 (Y[0]), .S (Select), .Q (Out[0]));
endmodule

module ccu(clk, reset, A, B, sum, cout);
  input clk, reset;
  input [1:0] A, B;
  output [1:0] sum;
  output cout;
  wire clk, reset;
  wire [1:0] A, B;
  wire [1:0] sum;
  wire cout;
  wire [1:0] m_out1;
  wire [1:0] m_out2;
  wire [1:0] count;
  adder a1(.A (m_out1), .B (m_out2), .Sum (sum), .Cout (cout));
  counter c1(.clk (clk), .reset (reset), .out (count));
  mux m1(.Select (count[1]), .X (A), .Y (B), .Out (m_out1));
  mux_1 m2(.Select (count[0]), .X (B), .Y (A), .Out (m_out2));
endmodule

