######################################################################

# Created by Encounter(R) RTL Compiler v11.20-s017_1 on Wed Oct 28 19:21:46 -0400 2015

# This file contains the RC script for /designs/ccu

######################################################################

set_attribute -quiet gui_auto_update false /
set_attribute -quiet lib_search_path /homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/ /
set_attribute -quiet script_search_path /homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/ /
set_attribute -quiet hdl_search_path /homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/ /
set_attribute -quiet use_area_from_lef true /
set_attribute -quiet hdl_track_filename_row_col true /
set_attribute -quiet ple_correlation_factors {1.9000 2.0000} /
set_attribute -quiet maximum_interval_of_vias infinity /
set_attribute -quiet ple_mode global /
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AND2X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AND2X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AND2X4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AND3X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AND3X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AND3X4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AND4X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AND4X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AND4X4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/ANTENNA
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AO21X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AO21X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AO221X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AO221X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AO222X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AO222X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AO22X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AO22X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AOBUFX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AOBUFX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AOBUFX4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AODFFARX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AODFFARX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AODFFNARX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AODFFNARX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AOI21X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AOI21X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AOI221X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AOI221X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AOI222X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AOI222X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AOI22X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AOI22X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AOINVX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AOINVX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/AOINVX4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/BSLEX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/BSLEX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/BSLEX4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/BUSKP
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/CLOAD1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DCAP
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DEC24X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DEC24X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DELLN1X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DELLN2X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DELLN3X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFARX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFARX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFASRX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFASRX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFASX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFASX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFNARX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFNARX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFNASRNX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFNASRNX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFNASRQX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFNASRQX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFNASRX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFNASRX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFNASX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFNASX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFNX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFNX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFSSRX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFSSRX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DFFX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DHFILLHLH2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DHFILLHLHLS11
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/DHFILLLHL2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/FADDX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/FADDX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/HADDX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/HADDX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/HEAD2X16
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/HEAD2X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/HEAD2X32
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/HEAD2X4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/HEAD2X8
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/HEADX16
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/HEADX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/HEADX32
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/HEADX4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/HEADX8
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/IBUFFX16
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/IBUFFX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/IBUFFX32
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/IBUFFX4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/IBUFFX8
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/INVX0
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/INVX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/INVX16
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/INVX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/INVX32
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/INVX4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/INVX8
set_attribute -quiet is_isolation_cell true /libraries/saed90nm_typ/libcells/ISOLANDX1
set_attribute -quiet valid_location to /libraries/saed90nm_typ/libcells/ISOLANDX1
set_attribute -quiet is_isolation_cell true /libraries/saed90nm_typ/libcells/ISOLANDX2
set_attribute -quiet valid_location to /libraries/saed90nm_typ/libcells/ISOLANDX2
set_attribute -quiet is_isolation_cell true /libraries/saed90nm_typ/libcells/ISOLANDX4
set_attribute -quiet valid_location to /libraries/saed90nm_typ/libcells/ISOLANDX4
set_attribute -quiet is_isolation_cell true /libraries/saed90nm_typ/libcells/ISOLANDX8
set_attribute -quiet valid_location to /libraries/saed90nm_typ/libcells/ISOLANDX8
set_attribute -quiet is_isolation_cell true /libraries/saed90nm_typ/libcells/ISOLORX1
set_attribute -quiet valid_location to /libraries/saed90nm_typ/libcells/ISOLORX1
set_attribute -quiet is_isolation_cell true /libraries/saed90nm_typ/libcells/ISOLORX2
set_attribute -quiet valid_location to /libraries/saed90nm_typ/libcells/ISOLORX2
set_attribute -quiet is_isolation_cell true /libraries/saed90nm_typ/libcells/ISOLORX4
set_attribute -quiet valid_location to /libraries/saed90nm_typ/libcells/ISOLORX4
set_attribute -quiet is_isolation_cell true /libraries/saed90nm_typ/libcells/ISOLORX8
set_attribute -quiet valid_location to /libraries/saed90nm_typ/libcells/ISOLORX8
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/LARX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/LARX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/LASRNX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/LASRNX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/LASRQX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/LASRQX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/LASRX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/LASRX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/LASX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/LASX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/LATCHX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/LATCHX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/LNANDX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/LNANDX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/MUX21X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/MUX21X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/MUX41X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/MUX41X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NAND2X0
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NAND2X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NAND2X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NAND2X4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NAND3X0
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NAND3X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NAND3X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NAND3X4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NAND4X0
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NAND4X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NBUFFX16
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NBUFFX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NBUFFX32
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NBUFFX4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NBUFFX8
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NMT1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NMT2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NMT3
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NOR2X0
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NOR2X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NOR2X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NOR2X4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NOR3X0
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NOR3X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NOR3X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NOR3X4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NOR4X0
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/NOR4X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OA21X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OA21X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OA221X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OA221X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OA222X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OA222X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OA22X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OA22X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OAI21X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OAI21X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OAI221X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OAI221X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OAI222X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OAI222X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OAI22X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OAI22X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OR2X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OR2X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OR2X4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OR3X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OR3X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OR3X4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OR4X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OR4X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/OR4X4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/PGX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/PGX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/PGX4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/PMT1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/PMT2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/PMT3
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFARX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFARX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFASRSX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFASRSX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFASRX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFASRX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFASX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFASX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFNARX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFNARX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFNASRX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFNASRX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFNASX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFNASX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFNX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFNX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFSSRX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFSSRX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SDFFX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SHFILL1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SHFILL128
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SHFILL2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SHFILL3
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/SHFILL64
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/TIEH
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/TIEL
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/TNBUFFX1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/TNBUFFX16
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/TNBUFFX2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/TNBUFFX32
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/TNBUFFX4
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/TNBUFFX8
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/XNOR2X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/XNOR2X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/XNOR3X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/XNOR3X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/XOR2X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/XOR2X2
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/XOR3X1
set_attribute -quiet valid_location {} /libraries/saed90nm_typ/libcells/XOR3X2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/CGLPPSX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/CGLPPSX4
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFNSRASX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFNSRX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFNSRX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFSRARX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFSRARX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFSRASRX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/CGLPPSX8
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFSRASRX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/CGLNPRX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/CGLNPRX8
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/CGLNPSX16
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/CGLNPSX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/CGLNPSX4
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/CGLNPSX8
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/CGLPPRX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/CGLPPRX8
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSUPENCLX4
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/CGLPPSX16
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSUPENCLX8
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSUPENX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSUPENX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSUPENX4
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSUPENX8
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSUPX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSUPX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSUPX4
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSUPX8
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFNSRARX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFNSRARX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFNSRASRNX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFNSRASRNX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFNX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFNX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFNSRASX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFNX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFNX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFSRSSRX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFSRSSRX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFSRX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFSRX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNENCLX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNENCLX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNENCLX4
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNENCLX8
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNENX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNENX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNENX4
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNENX8
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNX4
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNX8
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSUPENCLX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSUPENCLX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFNSRARX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFNSRARX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFNSRASRNX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFNSRASRNX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFNSRASRQX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFNSRASRQX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFNSRASRX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFNSRASRX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFNSRASX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFNSRASX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFNSRX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFNSRX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFSRARX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFSRARX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFSRASRX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFSRASRX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFSRASX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFSRASX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFSRSSRX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFSRSSRX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFSRX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFSRX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFSRASX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFSRASX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFNSRASRQX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFNSRASRQX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFNSRASRX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFNSRASRX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNSSX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNSSX4
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFARX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFARX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFNARX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RDFFNARX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFARX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFARX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFNARX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/RSDFFNARX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNSSX8
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/ISOLANDAOX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/ISOLANDAOX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/ISOLANDAOX4
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/ISOLANDAOX8
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/ISOLORAOX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/ISOLORAOX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/ISOLORAOX4
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/ISOLORAOX8
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNENCLSSX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNENCLSSX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNENCLSSX4
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNENCLSSX8
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNENSSX1
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNENSSX2
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNENSSX4
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNENSSX8
set_attribute -quiet valid_location {} /libraries/physical_cells/libcells/LSDNSSX1
set_attribute -quiet wireload_selection /libraries/saed90nm_typ/wireload_selections/predcaps /
set_attribute -quiet tree_type balanced_tree /libraries/saed90nm_typ/operating_conditions/TYPICAL
set_attribute -quiet tree_type balanced_tree /libraries/saed90nm_typ/operating_conditions/_nominal_
# BEGIN MSV SECTION
# END MSV SECTION
# BEGIN DFT SECTION
set_attribute -quiet dft_scan_style muxed_scan /
set_attribute -quiet dft_scanbit_waveform_analysis false /
# END DFT SECTION
set_attribute -quiet hdl_user_name ccu /designs/ccu
set_attribute -quiet hdl_filelist {{default -v1995 {SYNTHESIS} {/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/counter.v}} {default -v2001 {SYNTHESIS} {/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/mux.v}} {default -v1995 {SYNTHESIS} {/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/adder.v}} {default -v1995 {SYNTHESIS} {/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/ccu.v}}} /designs/ccu
set_attribute -quiet ovf_current_verification_directory fv/ccu /designs/ccu
set_attribute -quiet arch_filename /homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/ccu.v /designs/ccu
set_attribute -quiet entity_filename /homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/ccu.v /designs/ccu
set_attribute -quiet hdl_user_name adder /designs/ccu/subdesigns/adder
set_attribute -quiet hdl_filelist {{default -v1995 {SYNTHESIS} {/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/adder.v}}} /designs/ccu/subdesigns/adder
set_attribute -quiet arch_filename /homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/adder.v /designs/ccu/subdesigns/adder
set_attribute -quiet entity_filename /homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/adder.v /designs/ccu/subdesigns/adder
set_attribute -quiet hdl_user_name counter /designs/ccu/subdesigns/counter
set_attribute -quiet hdl_filelist {{default -v1995 {SYNTHESIS} {/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/counter.v}}} /designs/ccu/subdesigns/counter
set_attribute -quiet arch_filename /homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/counter.v /designs/ccu/subdesigns/counter
set_attribute -quiet entity_filename /homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/counter.v /designs/ccu/subdesigns/counter
set_attribute -quiet hdl_user_name mux /designs/ccu/subdesigns/mux
set_attribute -quiet hdl_filelist {{default -v2001 {SYNTHESIS} {/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/mux.v}}} /designs/ccu/subdesigns/mux
set_attribute -quiet arch_filename /homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/mux.v /designs/ccu/subdesigns/mux
set_attribute -quiet entity_filename /homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/mux.v /designs/ccu/subdesigns/mux
set_attribute -quiet hdl_user_name mux /designs/ccu/subdesigns/mux_1
set_attribute -quiet hdl_filelist {{default -v2001 {SYNTHESIS} {/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/mux.v}}} /designs/ccu/subdesigns/mux_1
set_attribute -quiet arch_filename /homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/mux.v /designs/ccu/subdesigns/mux_1
set_attribute -quiet entity_filename /homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/mux.v /designs/ccu/subdesigns/mux_1
set_attribute -quiet file_row_col {{/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/ccu.v 22 10}} /designs/ccu/instances_hier/a1
set_attribute -quiet file_row_col {{/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/ccu.v 18 12}} /designs/ccu/instances_hier/c1
set_attribute -quiet file_row_col {{/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/counter.v 18 15}} {/designs/ccu/instances_hier/c1/instances_seq/out_reg[1]}
set_attribute -quiet file_row_col {{/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/counter.v 22 13}} {/designs/ccu/instances_hier/c1/instances_seq/out_reg[0]}
set_attribute -quiet file_row_col {{/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/counter.v 18 15}} /designs/ccu/instances_hier/c1/instances_comb/g81
set_attribute -quiet file_row_col {{/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/counter.v 18 15}} /designs/ccu/instances_hier/c1/instances_comb/g82
set_attribute -quiet file_row_col {{/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/counter.v 18 15}} /designs/ccu/instances_hier/c1/instances_comb/g83
set_attribute -quiet file_row_col {{/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/counter.v 18 15}} /designs/ccu/instances_hier/c1/instances_comb/g84
set_attribute -quiet file_row_col {{/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/ccu.v 19 8}} /designs/ccu/instances_hier/m1
set_attribute -quiet file_row_col {{/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/mux.v 13 14}} /designs/ccu/instances_hier/m1/instances_comb/g33
set_attribute -quiet file_row_col {{/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/mux.v 13 14}} /designs/ccu/instances_hier/m1/instances_comb/g34
set_attribute -quiet file_row_col {{/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/ccu.v 21 8}} /designs/ccu/instances_hier/m2
set_attribute -quiet file_row_col {{/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/mux.v 13 14}} /designs/ccu/instances_hier/m2/instances_comb/g33
set_attribute -quiet file_row_col {{/homes/etaylor5/enee408c_user/labs/lab08/verilog/ccu/syn/mux.v 13 14}} /designs/ccu/instances_hier/m2/instances_comb/g34
