name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  javascript-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install
      run: npm i prettier
    - name: Lint Frontend
      run: npx prettier -c ./frontend
    - name: Lint Backend
      run: npx prettier -c ./backend
