#!/usr/bin/env bash

# Build one module
function makeone {
	if ! [ -d ../../bin/counter ]; then
		mkdir ../../bin/counter
	fi	
	vlib ../../bin/counter
	vmap work ../../bin/counter
	vlog -work ../../bin/counter $1.v
}

# Build modules
makeone counter
