#!/usr/bin/env bash

# Script to run this test
# Usage: runme [no arguments]

# [FIXME: complete this script, this is just a template]

UXLIB=../../bin/structural

if [ -f out.txt ]; then
	rm -r out.txt
fi

vsim -c -L "$UXLIB" -lic_plus -quiet -novopt -do simulate-do testbench > transcript
cat out.txt

